### ISSUE TITLE
Revert to readr::write_csv for any CSV writing within the workflow

### ISSUE THREAD

**Issue by eblondel** [firms-gta/geoflow-tunaatlas#3]
@BastienIRD we had discussed this in the past, please make sure to revert from `fwrite` (which is from `data.table`) to `readr::write_csv`.

The package `data.table` should not be a dependency of the base firms-gta workflow. It is essentially tailored to reporting (either markdown or shiny). I see you added a comment to explain why you used this, ie the number of digits, but this should not be managed through csv writing, but just at reporting level.

Thanks

**Comment by BastienIRD** [comment]
The ancient script was actually writing CSV files using the utils::write.csv function, not using the readr::write_csv. The issue was not only about decimals (this was the only thing that could get us clues about the issue) but about the size of the CSV written which couldn't be loaded in the sdilab database. 
I will change all the .csv writing with readr::write_csv, however, it will be a new commit, not a revert. Also, it will add the "readr" dependency if it was not already the case.

**Comment by BastienIRD** [comment]
Just realized that the data.table package is also called in some geoflow-tunaatlas functions (with the setDT function). Thus, data.table was already a dependency of the base firms-gta workflow. Should we remove all the used data.frame functions ?

**Comment by eblondel** [comment]
setDT is not really the best thing here, but thanks for pointing out. In general we should reduce the number of dependencies, especially those that are not tailored to processing but more to rendering. The map codelist is a function coming from the rtunaatlas if i'm not wrong, and with the work of harmonization/standardization done by RFMOs, we will not have to map codelists anymore.

whenever we write CSV it's better to rely on readr, which is the most standard solution for now.

**Comment by BastienIRD** [comment]
I see, however as it is not done by RFMOs yet we will use the function for at least the next GTA update.
I have seen that setDT() could be, to some extent, replaced by data.frame(). I can change it, however, the dependencies that I am raising could be numerous (reshape2 as well, which I did not expect). I'll clean this up and let you know if for some reason I cannot manage to get rid of some packages used.

**Comment by eblondel** [comment]
I don't ask to change the `setDT`. We can leave it as it is. No need either to invest in refactoring this code that will not be used in the next GTA update. But whenever we use fwrite it's better to get rid of this dependency and use readr::write_csv.

**Comment by eblondel** [comment]
reshape2 will also disappear, and even if we would like to do reshaping, reshape2 is not needed, it's matter of using the base R, that in many areas was not used unfortunately.
