### ISSUE TITLE
Local action with local path does not allow specifiying directory for jobs

### ISSUE THREAD

**Issue by bastienird** [firms-gta/geoflow-tunaatlas#30]
We cannot specify a directory for jobs if a local action is defined with a local path. (ex : ./tunaatlas_script/load_dataset.R) 

**executeWorkflow("tunaatlas_qa_global_datasets_catch.json", dir ="tunaatlas_qa_global_datasets_catch")**

_Error:_

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/home/grasset/Documents/geoflow-tunaatlas/tunaatlas_qa_global_datasets_catch/./tunaatlas_actions/load_dataset.R': No such file or directory

**Comment by BastienIRD** [comment]
I would suggest to use GitHub path to fix this, however, if we want to keep the local path for any reason I can move this issue to the geoflow repository.

**Comment by eblondel** [comment]
AFAIR, in geoflow, local actions can't be set with relative paths.
You refer to `load_dataset`, it's not a local action, but a global action. It seems to relate to the small enhancement I made recently to be able to use relative paths for custom global action (See https://github.com/r-geoflow/geoflow/issues/327); so what you say is that when using relative paths, combined with a `dir` where to store the jobs, it doesn't work, do you confirm?

**Comment by BastienIRD** [comment]
Sorry, I do refer to load_dataset and I meant global action. Yes, when using a relative path, combined with a dir where to store a job it doesn't work even though it is working without providing a dir. However, is there any reason to use a relative path instead of a GitHub one? (in this case)

**Comment by eblondel** [comment]
yes very good reasons, we should be able to test actions with ongoing modifications, without the need to commit them to be able to test them.

**Comment by eblondel** [comment]
i've reopened the ticket on geoflow and applied a tentative fix. you 'll let me know
