### ISSUE TITLE
Updating spatial harmonization code for CCSBT pre-harmonisation data

### ISSUE THREAD

**Issue by bastienird** [firms-gta/geoflow-tunaatlas#7]
Issues

- [x] Pre-harmonization of the CCSBT data results in creating 7 grids with impossible code in view of the CWP convention. The harmo_spatial_5 function may be offsetting georeferenced data.
- [ ] Assignation of CWP quadrants is wrong at latitude and longitude 0

**Comment by eblondel** [comment]
@BastienIRD i've reviewed your code, it seems fine except the lat min/max that you set to define the quadrants. shoud be -90/90 instead of -180/180. Let me know when you have tested this, and check the resulting grid codes.

**Comment by BastienIRD** [comment]
Effectively, thanks @eblondel for raising this issue that was as well in the harmo_spatial_4 function. The outputted codes are not coded XXXXX180 anymore and the harmo_spatial_5 and harmo_spatial_4 are now working fine. 
Just so you know, this error was not creating any issues in IATTC data for the last GTA update as no record had abs(latitude) > 90 (hopefully)
